version: '3.8'

services:
  web:
    container_name: ${COOLIFY_CONTAINER_NAME:-omni-fit}
    image: ${DOCKER_REGISTRY_IMAGE:-omni-fit}:${SOURCE_COMMIT:-latest}
    build:
      context: ../../../  # Remonte à la racine du monorepo
      dockerfile: Dockerfile.omnifit
      args:
        # Variables Vite build-time
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_APP_URL=${VITE_APP_URL:-https://fit.omnirealm.tech}
        - VITE_LEMONSQUEEZY_STORE_ID=${VITE_LEMONSQUEEZY_STORE_ID}
        - VITE_LEMONSQUEEZY_WEBHOOK_SECRET=${VITE_LEMONSQUEEZY_WEBHOOK_SECRET}
    ports:
      - '3003:80'
    environment:
      # Nginx ne nécessite pas de variables d'environnement runtime
      # Les variables Vite sont intégrées au build
      - COOLIFY_URL=${COOLIFY_URL:-localhost}
      - COOLIFY_FQDN=${COOLIFY_FQDN:-localhost}
      - COOLIFY_BRANCH=${COOLIFY_BRANCH:-main}
      - SOURCE_COMMIT=${SOURCE_COMMIT:-latest}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s